title: INDI Technical Documentation
lang: en
description: Docs on how to create INDI drivers and clients.

remote_theme: just-the-docs/just-the-docs
exclude:
  - CNAME
  - drivers/examples
  - vendor/
