name: 404 links

on: [push]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check links
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --exclude-mail --timeout 20 --exclude "sourceforge.net" --exclude "gnu.org" "**/*.md"
